spring:
  datasource:
    url: jdbc:h2:mem:todo
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 395539887047-n18ulobd0hhnthpmjb8cnkulpodoo33s.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
server:
  error:
    include-stacktrace: never
logging:
  level:
    org.springframework.security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,metrics